require:
    - rubocop-rspec
    - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0.3
  NewCops: enable
  Exclude:
    - "spec/dummy/bin/**/*"

Style/Documentation:
    Enabled: false
